version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - default
      - common


  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    links:
      - db

networks:
  common:
    external: true